#!/usr/bin/env python3
"""Generate images-fx.h with hardcoded bopti MONO images for the fx-9860G."""
from PIL import Image

import os

SRC = [
    ("bongocat.jpg", "img_cat"),
    ("bongocat-r.jpg", "img_cat_r"),
    ("bongocat-l.jpg", "img_cat_l"),
    ("bongocat-lr.jpg", "img_cat_lr"),
]
W, H = 101, 64
CROP = (45, 0, 215, 108)
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "src", "images-fx.h")


def make_bopti_mono(path):
    """Replicate fxconv convert_bopti_fx for profile 'mono' (id 0)."""
    img = Image.open(path).convert("L")
    img = img.crop(CROP)
    img = img.resize((W, H), Image.LANCZOS)

    w = (W + 31) // 32
    data = bytearray(4 * w * H)
    px = img.load()
    for y in range(H):
        for x in range(W):
            if px[x, y] < 128:
                data[4 * y * w + (x >> 3)] |= (1 << (~x & 7))

    return bytes(data)


def emit_array(name, data, f):
    f.write(f"static const uint8_t {name}_data[{len(data)}] __attribute__((aligned(4))) = {{\n")
    for i in range(0, len(data), 16):
        f.write("  " + " ".join(f"0x{b:02x}," for b in data[i:i+16]) + "\n")
    f.write("};\n\n")


def main():
    with open(OUT, "w") as f:
        f.write("/* Generated by gen-images.py - do not edit */\n")
        f.write("#include <gint/display-fx.h>\n\n")
        for path, name in SRC:
            raw = make_bopti_mono(path)
            emit_array(name, raw, f)
        f.write("#define IMG_FX_W 116\n")
        f.write("#define IMG_FX_H 64\n\n")
        for _, name in SRC:
            f.write(f"static const bopti_image_t {name} = {{\n")
            f.write(f"  .gray = 0, .profile = IMAGE_MONO,\n")
            f.write(f"  .width = IMG_FX_W, .height = IMG_FX_H,\n")
            f.write(f"  .data = (uint8_t *){name}_data,\n")
            f.write("};\n\n")


main()